/**
 * TradingGlossary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateGlossaryLetterDto } from '../model/models';
import { GlossaryLetterDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { UpdateGlossaryLetterDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GlossaryLetterGeneratedServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/GlossaryLetter
     * @param createGlossaryLetterDto 
     */
    createGlossaryLetter(createGlossaryLetterDto?: CreateGlossaryLetterDto, extraHttpRequestParams?: any): Observable<GlossaryLetterDto>;

    /**
     * 
     * 
     * @endpoint delete /api/GlossaryLetter/{id}
     * @param id 
     */
    deleteGlossaryLetter(id: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @endpoint get /api/GlossaryLetter/{id}
     * @param id 
     */
    getGlossaryLetterById(id: number, extraHttpRequestParams?: any): Observable<GlossaryLetterDto>;

    /**
     * 
     * 
     * @endpoint get /api/GlossaryLetter
     */
    getGlossaryLetters(extraHttpRequestParams?: any): Observable<Array<GlossaryLetterDto>>;

    /**
     * 
     * 
     * @endpoint put /api/GlossaryLetter/{id}
     * @param id 
     * @param updateGlossaryLetterDto 
     */
    updateGlossaryLetter(id: number, updateGlossaryLetterDto?: UpdateGlossaryLetterDto, extraHttpRequestParams?: any): Observable<GlossaryLetterDto>;

}
