/**
 * TradingGlossary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateGlossaryEntryDto } from '../model/models';
import { GlossaryEntryDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { UpdateGlossaryEntryDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GlossaryEntryGeneratedServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/GlossaryEntry
     * @param createGlossaryEntryDto 
     */
    createGlossaryEntry(createGlossaryEntryDto?: CreateGlossaryEntryDto, extraHttpRequestParams?: any): Observable<GlossaryEntryDto>;

    /**
     * 
     * 
     * @endpoint delete /api/GlossaryEntry/{id}
     * @param id 
     */
    deleteGlossaryEntry(id: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @endpoint get /api/GlossaryEntry
     */
    getGlossaryEntries(extraHttpRequestParams?: any): Observable<Array<GlossaryEntryDto>>;

    /**
     * 
     * 
     * @endpoint get /api/GlossaryEntry/letter/{letterId}
     * @param letterId 
     */
    getGlossaryEntriesByLetterId(letterId: number, extraHttpRequestParams?: any): Observable<Array<GlossaryEntryDto>>;

    /**
     * 
     * 
     * @endpoint get /api/GlossaryEntry/{id}
     * @param id 
     */
    getGlossaryEntryById(id: number, extraHttpRequestParams?: any): Observable<GlossaryEntryDto>;

    /**
     * 
     * 
     * @endpoint put /api/GlossaryEntry/{id}
     * @param id 
     * @param updateGlossaryEntryDto 
     */
    updateGlossaryEntry(id: number, updateGlossaryEntryDto?: UpdateGlossaryEntryDto, extraHttpRequestParams?: any): Observable<GlossaryEntryDto>;

}
