/**
 * TradingGlossary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateGlossaryTagDto } from '../model/models';
import { GlossaryTagDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { UpdateGlossaryTagDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GlossaryTagGeneratedServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/GlossaryTag
     * @param createGlossaryTagDto 
     */
    createGlossaryTag(createGlossaryTagDto?: CreateGlossaryTagDto, extraHttpRequestParams?: any): Observable<GlossaryTagDto>;

    /**
     * 
     * 
     * @endpoint delete /api/GlossaryTag/{id}
     * @param id 
     */
    deleteGlossaryTag(id: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @endpoint get /api/GlossaryTag
     */
    getGlossaryTags(extraHttpRequestParams?: any): Observable<Array<GlossaryTagDto>>;

    /**
     * 
     * 
     * @endpoint put /api/GlossaryTag
     * @param updateGlossaryTagDto 
     */
    updateGlossaryTag(updateGlossaryTagDto?: UpdateGlossaryTagDto, extraHttpRequestParams?: any): Observable<GlossaryTagDto>;

}
