/**
 * TradingGlossary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlossaryEntryTag } from './glossaryEntryTag';


export interface GlossaryTag { 
    id: number;
    createdAt: Date;
    createdBy: string;
    modifiedAt: Date | null;
    modifiedBy: string | null;
    label: string;
    sortOrder: number;
    glossaryEntryTags: Array<GlossaryEntryTag>;
}

