/**
 * TradingGlossary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlossaryEntry } from './glossaryEntry';


export interface GlossaryLetterDto { 
    id: number;
    code: string;
    label: string;
    sortOrder: number;
    createdAt: Date;
    createdBy: string;
    modifiedAt: Date | null;
    modifiedBy: string | null;
    glossaryEntries: Array<GlossaryEntry>;
}

