/**
 * TradingGlossary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GlossaryEntryDto { 
    title: string;
    description: string | null;
    createdAt: Date;
    createdBy: string;
    modifiedAt: Date | null;
    modifiedBy: string | null;
}

