/**
 * TradingGlossary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlossaryTag } from './glossaryTag';
import { GlossaryEntry } from './glossaryEntry';


export interface GlossaryEntryTag { 
    glossaryEntryId: number;
    glossaryTagId: number;
    glossaryEntry: GlossaryEntry;
    glossaryTag: GlossaryTag;
}

