/**
 * TradingGlossary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlossaryLetter } from './glossaryLetter';
import { GlossaryEntryTag } from './glossaryEntryTag';


export interface GlossaryEntry { 
    id: number;
    createdAt: Date;
    createdBy: string;
    modifiedAt: Date | null;
    modifiedBy: string | null;
    glossaryLetterId: number;
    glossaryLetter: GlossaryLetter;
    title: string;
    description: string | null;
    glossaryEntryTags: Array<GlossaryEntryTag>;
}

